version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pgsql
    networks:
      - laravel

  pgsql:
    image: postgres:9.4-alpine
    container_name: pgsql
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: homestead
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  service_a:
    image: nginx:stable-alpine
    container_name: service_a
    ports:
      - "9001:9000"
    networks:
      - laravel

  service_b:
    image: nginx:stable-alpine
    container_name: service_b
    ports:
      - "9002:9000"
    networks:
      - laravel

  service_c:
    image: nginx:stable-alpine
    container_name: service_c
    ports:
      - "9003:9000"
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - pgsql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel
